[2012-07-19 11:51:11] request.INFO: Matched route "blog_post_index" (parameters: "_controller": "Webdev\BlogBundle\Controller\PostController::indexAction", "_route": "blog_post_index") [] []
[2012-07-19 11:51:11] request.CRITICAL: InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package. (uncaught exception) at /Users/marc/Sites/blog/vendor/doctrine-common/lib/Doctrine/Common/Annotations/FileCacheReader.php line 46 [] []
[2012-07-19 11:51:11] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package.) [] []
[2012-07-19 11:51:13] request.INFO: Matched route "blog_post_index" (parameters: "_controller": "Webdev\BlogBundle\Controller\PostController::indexAction", "_route": "blog_post_index") [] []
[2012-07-19 11:51:13] request.CRITICAL: InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package. (uncaught exception) at /Users/marc/Sites/blog/vendor/doctrine-common/lib/Doctrine/Common/Annotations/FileCacheReader.php line 46 [] []
[2012-07-19 11:51:13] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package.) [] []
[2012-07-19 11:51:14] request.INFO: Matched route "blog_post_index" (parameters: "_controller": "Webdev\BlogBundle\Controller\PostController::indexAction", "_route": "blog_post_index") [] []
[2012-07-19 11:51:14] request.CRITICAL: InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package. (uncaught exception) at /Users/marc/Sites/blog/vendor/doctrine-common/lib/Doctrine/Common/Annotations/FileCacheReader.php line 46 [] []
[2012-07-19 11:51:14] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "/Users/marc/Sites/blog/app/cache/prod/annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package.) [] []
[2012-07-23 18:23:29] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sonataadmin" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:23:29] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:23:34] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sonataadmin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:23:34] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:23:37] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sonataadmin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:23:37] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:24:11] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /admin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:24:11] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:24:12] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /admin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:24:12] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:24:13] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /admin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:24:13] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:24:15] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:24:15] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-23 18:24:17] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/dashboard" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-23 18:24:17] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:21:22] request.INFO: Matched route "admin_webdev_blog_post_list" (parameters: "_controller": "Sonata\AdminBundle\Controller\CRUDController::listAction", "_sonata_admin": "webdev.blog.admin.post", "_sonata_name": "admin_webdev_blog_post_list", "_route": "admin_webdev_blog_post_list") [] []
[2012-07-24 10:21:22] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-07-24 10:21:22] request.CRITICAL: Symfony\Component\Form\Exception\UnexpectedTypeException: Expected argument of type "string or Symfony\Component\Form\FormTypeInterface", "boolean" given (uncaught exception) at /Users/marc/Sites/blog/vendor/symfony/src/Symfony/Component/Form/FormBuilder.php line 552 [] []
[2012-07-24 10:21:22] security.DEBUG: Write SecurityContext in the session [] []
[2012-07-24 10:21:29] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:21:29] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:21:33] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:21:33] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:21:40] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:21:40] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:21:55] request.INFO: Matched route "admin_webdev_blog_post_list" (parameters: "_controller": "Sonata\AdminBundle\Controller\CRUDController::listAction", "_sonata_admin": "webdev.blog.admin.post", "_sonata_name": "admin_webdev_blog_post_list", "_route": "admin_webdev_blog_post_list") [] []
[2012-07-24 10:21:55] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-07-24 10:21:56] request.CRITICAL: Symfony\Component\Form\Exception\UnexpectedTypeException: Expected argument of type "string or Symfony\Component\Form\FormTypeInterface", "boolean" given (uncaught exception) at /Users/marc/Sites/blog/vendor/symfony/src/Symfony/Component/Form/FormBuilder.php line 552 [] []
[2012-07-24 10:21:56] security.DEBUG: Write SecurityContext in the session [] []
[2012-07-24 10:38:51] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:38:51] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:38:56] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:38:56] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:39:05] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:39:05] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:39:08] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:39:08] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:39:19] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:39:19] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:39:31] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/webdev/blog/post/Array" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:39:32] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-07-24 10:41:37] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin/" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-07-24 10:41:37] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-08-16 12:12:01] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /sadmin" (uncaught exception) at /Users/marc/Sites/blog/app/cache/prod/classes.php line 4434 [] []
[2012-08-16 12:12:01] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "/Users/marc/Sites/blog/app/Resources/views/base.html.twig" at line 89.) [] []
[2012-08-20 14:18:42] request.INFO: Matched route "blog_post_index" (parameters: "_controller": "Webdev\BlogBundle\Controller\PostController::indexAction", "_route": "blog_post_index") [] []
[2012-08-20 14:18:42] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-08-20 14:18:47] request.CRITICAL: PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (uncaught exception) at /Users/marc/Sites/blog/vendor/doctrine-dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 36 [] []
[2012-08-20 14:18:47] security.DEBUG: Write SecurityContext in the session [] []
[2012-08-20 14:19:38] request.INFO: Matched route "blog_post_index" (parameters: "_controller": "Webdev\BlogBundle\Controller\PostController::indexAction", "_route": "blog_post_index") [] []
[2012-08-20 14:19:38] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2012-08-20 14:19:43] request.CRITICAL: PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (uncaught exception) at /Users/marc/Sites/blog/vendor/doctrine-dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 36 [] []
[2012-08-20 14:19:43] security.DEBUG: Write SecurityContext in the session [] []
